# автозапуск
exec-once = hyprpaper
exec-once = waybar
exec-once = hyprpaper
# Установка темного режима интерфейса
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Установка правильного имени темы (для adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
env = GTK_THEME,adw-gtk3-dark

# Увеличение и уменьшение яркости (Fn + F5 / Fn + F6)
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Управление звуком (Fn + F10 / F11 / F12)
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1.0

# Переменные
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin

# Скриншоты через Hyprshot
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots
bind = , Print, exec, hyprshot -m region

# Переключение столов в любую сторону (создает новые пустые столы)
bind = $mainMod, mouse_up, workspace, r+1
bind = $mainMod, mouse_down, workspace, r-1

# Hyprland фигня которую я не знаю как назвать
bind = ALT, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, R, exec, rofi -show drun

# Программы
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, F, exec, firefox
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, T, exec, telegram-desktop
bind = $mainMod, D, exec, discord
bind = $mainMod, S, exec, steam
bind = $mainMod, H, exec, happ

# Окна
#  Передвинуть окна
bind = $mainMod, left, movewindow, l
bind = $mainMod, right, movewindow, r
bind = $mainMod, up, movewindow, u
bind = $mainMod, down, movewindow, d

#  Вид окон
decoration {
    rounding = 12
}

bind = $mainMod, 2, fullscreen, 1

general {
    gaps_in = 5
    gaps_out = 10
}

# Расскладка
input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =
}
